### ISSUE TITLE
High memory consumption for UDP associations on Linux (OpenWRT)

### ISSUE THREAD

**Issue by f4nff** [shadowsocks/shadowsocks-rust#745] opened 2022-01-16 11:25 UTC
Test equipment: r4s
Test system: openwrt

[https://github.com/shadowsocks/shadowsocks-rust/suites/4952439929/artifacts/143776137](https://github.com/shadowsocks/shadowsocks-rust/suites/4952439929/artifacts/143776137)
download:https://github.com/shadowsocks/shadowsocks-rust/actions/runs/1703977841

/etc/sysctl.d/11-nf-conntrack.conf

```
# Do not edit, changes to this file will be lost on upgrades
# /etc/sysctl.conf can be used to customize sysctl settings

net.netfilter.nf_conntrack_acct=1
net.netfilter.nf_conntrack_checksum=0
net.netfilter.nf_conntrack_max=1020000
net.netfilter.nf_conntrack_tcp_timeout_established=7440
net.netfilter.nf_conntrack_udp_timeout=60
net.netfilter.nf_conntrack_udp_timeout_stream=180
```

`/root/socks/sslocal --protocol tun -s "[::1]:8388" -m "aes-256-gcm" -k "hello-kitty" --outbound-bind-interface lo --tun-interface-name tun1 -U --udp-timeout 60 --udp-max-associations 65535`

`dns.exe -sr gddx.txt -at google.com -sl 6`

[dns-test.zip](https://github.com/shadowsocks/shadowsocks-rust/files/7876837/dns-test.zip)

Start dns to test for 30 seconds, then shut down.

Then wait for 5 minutes, after the number of connections drops,

<img width="638" alt="image" src="https://user-images.githubusercontent.com/19538878/149657891-bf68e47f-3b22-4adf-b79a-e7e87f9f8d0c.png">

<img width="413" alt="image" src="https://user-images.githubusercontent.com/19538878/149657901-3a848b4f-6e14-44bf-8251-a01e7d53250f.png">

Then it can be seen that sslocal occupies more than 400M of memory and will not continue to release,

**Comment by zonyitoo** [comment] 2022-01-16 11:33
I ran the [test tools](https://github.com/shadowsocks/shadowsocks-rust/tree/master/crates/shadowsocks-tools) nearly 15 minutes and didn't see memory occupied more than 7MiB. 400MiB is just impossible.

**Comment by f4nff** [comment] 2022-01-16 11:35
The reason why you did not exceed 7M is because you did not turn on UDP forwarding.

`-U --udp-timeout 60 --udp-max-associations 65535`

**Comment by zonyitoo** [comment] 2022-01-16 11:36
Of course I do enable the UDP relay. Just read the code I just provided and I have only sent UDP DNS queries.

**Comment by f4nff** [comment] 2022-01-16 11:38
That is, the mode in which your test tool sends data is too simple and not easy to trigger. I have given you the source code of my test tool. You can compile it yourself and try it.

**Comment by f4nff** [comment] 2022-01-16 11:38
Did you not see my screenshot? Am I cheating?

**Comment by zonyitoo** [comment] 2022-01-16 11:43
The `dns.exe` is not for OpenWRT, right? It is a NT32 program. The `dns.go` is the source code right?

**Comment by f4nff** [comment] 2022-01-16 11:44
`dns.go`  is the source code！

**Comment by f4nff** [comment] 2022-01-16 11:45
openwrt is used as a router, dns.exe is running under my windows 11 host,

**Comment by zonyitoo** [comment] 2022-01-16 11:49
My test code is exactly the same as yours. You didn't bind the outbound interface, which means that you will have to add route entries for your test name servers to make this test working.

I didn't see any difference between `dns.go` and [dns_pressure.rs](https://github.com/shadowsocks/shadowsocks-rust/blob/master/crates/shadowsocks-tools/src/dns_pressure.rs).

So instead of modifying your `dns.go`, I will run `dns_pressure` on my R4S with your provided sysctl configuration and see what would happened.

**Comment by zonyitoo** [comment] 2022-01-16 11:53
BTW, your `dns.go` will only open UDP sockets for sending queries, why there are so many TCP connections in your screenshots?

![image](https://user-images.githubusercontent.com/1067951/149658832-63d389d3-810b-4cdd-99bd-89cc78d9f56d.png)

**Comment by f4nff** [comment] 2022-01-16 11:56
The tcp connection is my other web browsing, I forward all the lan port connections.
When you request dns, request 208.67.222.222:443, not 208.67.222.222:53

**Comment by zonyitoo** [comment] 2022-01-16 12:12
Since we are talking about memory leak, it should be happening no matter what destination or what port you are using but just **creating UDP associations rapidly in a short time**.

Your `dns.go` is nothing just open a UDP socket to `208.67.222.222:443` and then send a DNS query message in plain (without any encryption). So there is just completely the same as `dns_pressure.rs`.

You cannot test it without a clean environment, may be the problem that you are facing is just completely unrelated to UDP, which is just wasting our time.

I am now going to run `dns_pressure` with nameserver `208.67.222.222:443`. The `sslocal` is running just like yours.

**Comment by f4nff** [comment] 2022-01-16 12:23
```
config interface 'tun1'
	option proto 'static'
	option ipaddr '10.255.0.1'
	option netmask '255.255.255.0'
	option device 'tun1'

config route
	option interface 'tun1'
	option target '0.0.0.0'
	option netmask '0.0.0.0'
	option gateway '10.255.0.1'
	option table '10'

config rule
	option in 'lan'
	option lookup '10'
	option priority '0'

```

/etc/config/network


`/root/socks/sslocal --protocol tun -s "[::1]:8388" -m "aes-256-gcm" -k "hello-kitty" --outbound-bind-interface lo --tun-interface-name tun1 -U --udp-timeout 60 --udp-max-associations 65535`


lan----windows 

`dns.exe -sr gddx.txt -at google.com -sl 6`

**Comment by f4nff** [comment] 2022-01-16 12:25
I have told you the test environment, and even the source code of the trigger. If you don't do it, you still question me.

If you follow your own logic, you will not find the problem.

Are the screenshots I gave you fake?

I can trigger, but you can't trigger, is this my problem or your problem?

**Comment by f4nff** [comment] 2022-01-16 12:25
I have reported several bugs to you, which one was not confirmed in the end?

**Comment by zonyitoo** [comment] 2022-01-16 12:33
You are reporting bugs to an opensource project. I am not paid and not full time working on it. If you just continue just like that I must have to solve your problem or I should do my best to service you, conversation ends here.

Remember, you are not a customer to me. We are just software developers.

I won't follow your configuration because you are adding variables and you test method is just nonsense.

And I can confirm that I can see nearly 400MiB RSS on R4S after opening 100 UDP clients sending queries continously (:

![image](https://user-images.githubusercontent.com/1067951/149659818-5439f2ce-6c76-4530-b879-0b88eaae7e0a.png)

But the memory consumption is stable and start to drop (the clients are still here):

![image](https://user-images.githubusercontent.com/1067951/149659997-d6ccd462-8682-4054-8154-2b8928a6938f.png)

The test is still running, and I cannot see any memory leak because memory usage is very stable.

So if you are willing to go on and see why it takes 400MiB to maintain 65536 UDP associations, we can go on. But I think I have already made a conclusion, there is no memory leak.

**Comment by f4nff** [comment] 2022-01-16 12:34
If these dns requests have closed the socket, shouldn't the memory be freed?

**Comment by f4nff** [comment] 2022-01-16 12:36
I have tested https://github.com/xjasonlyu/tun2socks , and the function is the same. After I concurrently make a dns request, the memory will fall back to more than 100M after 5 minutes. Rust should take up less memory.

**Comment by zonyitoo** [comment] 2022-01-16 12:36
Yes, they are freed after 60 seconds

![image](https://user-images.githubusercontent.com/1067951/149660163-78cb530d-7bdb-48d8-83a7-a24fddd7616d.png)

And yes, it is 100MiB on my R4S.

![image](https://user-images.githubusercontent.com/1067951/149660174-3c5b557b-de78-436e-a5bf-663e8a1c534f.png)

`lsof` shows that all the sockets are closed correctly.

**Comment by f4nff** [comment] 2022-01-16 12:37
When I just started sslocal, it took up less than 10M of memory, but after I requested a lot of dns, the memory fell back to less than 10M

**Comment by f4nff** [comment] 2022-01-16 12:39
I don't understand technology, I just ask my question, because the memory of the router is relatively small when it is thrown into openwrt, so I have such doubts.

**Comment by f4nff** [comment] 2022-01-16 12:43
<img width="316" alt="image" src="https://user-images.githubusercontent.com/19538878/149660380-b3aa297d-efd0-461e-9469-52cc9405eaf6.png">
<img width="944" alt="image" src="https://user-images.githubusercontent.com/19538878/149660396-74712d09-0293-40a0-9b45-babb9e2d92fe.png">

**Comment by f4nff** [comment] 2022-01-16 13:02
<img width="356" alt="image" src="https://user-images.githubusercontent.com/19538878/149660963-cc7496dd-b31a-463d-b7d6-55224aa0966e.png">

https://github.com/xjasonlyu/tun2socks

这是这个tun2socks，
VmHWM:   1370344 kB
VmRSS:    183384 kB

Peak 1.3G, will eventually fall back to 180M
----------------

The peak value of sslocal is 1.1G, and it can only fall back to 450M in the end.

**Comment by f4nff** [comment] 2022-01-16 13:03
I heard from others that rust will occupy less memory, but it can only fall back to 450M, so it will not continue. I want to know what he does with that memory, and why it is not returned to the system.

**Comment by zonyitoo** [comment] 2022-01-16 13:04
This is not a easy job to find out. I am now working on reviewing the code.

**Comment by f4nff** [comment] 2022-01-16 13:04
Ok, I'm not sure if this is a problem with the code, I'm just asking my own question.

**Comment by zonyitoo** [comment] 2022-01-16 13:08
Probably related to #608 .

**Comment by f4nff** [comment] 2022-01-16 13:13
I don't know what's going on. I have been using golang's tun2socks before, but go takes up a lot of memory, so I tried to use ssloacl, but the current performance seems to be worse.

**Comment by f4nff** [comment] 2022-01-16 14:09
<img width="339" alt="image" src="https://user-images.githubusercontent.com/19538878/149663453-48004fef-9308-4ec2-be61-15690247f2d9.png">

https://github.com/shadowsocks/shadowsocks-rust/actions/runs/1704368740

I tested this and it did not solve the problem, but the speed of reclaiming memory seems to be accelerated, but it also stops when it returns to around 450M.

**Comment by zonyitoo** [comment] 2022-01-16 14:11
It doesn't for fixing this issue, just an optimization that I found while reviewing.

**Comment by zonyitoo** [comment] 2022-01-16 14:26
[valgrind_sslocal.txt](https://github.com/shadowsocks/shadowsocks-rust/files/7877124/valgrind_sslocal.txt)

From this sample of memory leak detection, we can see no leaks. But it still cannot explain why RSS it remain so high even all the application allocated structures are released.

**Comment by zonyitoo** [comment] 2022-01-16 15:30
From massif, it is clearly that the memory was allocated by `tokio::spawn`:

![image](https://user-images.githubusercontent.com/1067951/149666501-22ae15c5-d895-40f9-adc6-23d9c3d98e2b.png)

**Comment by f4nff** [comment] 2022-01-16 15:38
I don't understand these details, can I solve it?

**Comment by zonyitoo** [comment] 2022-01-16 15:39
No you can't. I will do some experiments by moving this 16K buffer on heap.

**Comment by zonyitoo** [comment] 2022-01-16 16:02
Since every UDP associations requires at least one 64K (65536 bytes) buffer for receiving data from socket, so if we limits the total number of associations to `--udp-max-associations 65536`, then it requires memory `64K * 65536 = 4G`.

So it is expected that the `sslocal` consumes so many memory while doing DNS query tests.

Could we make the buffer smaller? 64K is too large? Maybe. Currently shadowsocks-rust follows the definition in [shadowsocks-libev](https://github.com/shadowsocks/shadowsocks-libev/blob/365465811113ed5018ee4c8d5b078b41095387fc/src/udprelay.h#L45), I don't think it is wise to change it now.

Now let's focus on why the memory allocator didn't return the memory even all the tasks are gone.

**Comment by f4nff** [comment] 2022-01-16 16:06
<img width="389" alt="image" src="https://user-images.githubusercontent.com/19538878/149667736-f5d7c894-0173-4000-a115-5e10cc87036f.png">
https://github.com/shadowsocks/shadowsocks-rust/commit/15c5f5d7b3f706d58958c9c560cfc6e29ff7e470
After testing, the maximum burst memory is only 250M, but it only dropped to 200M. I think the problem is why the memory is not released and returned to the system, not how much memory is occupied by the burst.

**Comment by f4nff** [comment] 2022-01-16 16:15
After you changed it just now, the memory usage is much smaller, but even if all tasks disappear, the problem of memory allocator not returning memory still exists.

**Comment by f4nff** [comment] 2022-01-16 16:23
<img width="394" alt="image" src="https://user-images.githubusercontent.com/19538878/149668459-7caec8ac-628f-4fc5-a364-33f407a05933.png">
**VmHWM:    157324 kB
VmRSS:    156588 kB**
I tested tcp concurrently with 10000, and it seems that the memory will not be released.

**Comment by zonyitoo** [comment] 2022-01-16 16:50
I checked with massif and heapcheck, all of them shows that nearly all the memory are probably released. So it is highly suspected that the Rust's memory allocator cached the memory without returning to OS.

Same problem was also discussed in: https://github.com/tokio-rs/tokio/discussions/2650

**Comment by f4nff** [comment] 2022-01-16 18:31
`/root/socks/sslocal --protocol tun -s5 "[::1]:8388" --outbound-bind-interface lo --tun-interface-name tun1 -U --udp-timeout 60 --udp-max-associations 65535`

It is recommended to add the s5 protocol to the tun mode. I have tested some new problems, but my comparison test is based on the transparent socks5 protocol.

If you test with 10,000 tcp requests concurrently, and then perform speedtest speed test, the rate will be very low!  But I use another golang tun2socks based on socks5 protocol but it won't.

**Comment by zonyitoo** [comment] 2022-01-17 04:29
Just keep in mind that this is a shadowsocks Project.

**Comment by zonyitoo** [comment] 2022-01-17 04:47
The performance issue may come from the new library `smoltcp`, which I just imported in refactoring. Just ignore it and I will make sure it is Ok when publishing a new version.

**Comment by f4nff** [comment] 2022-01-17 16:50
[https://github.com/wenjiax/stress](https://github.com/wenjiax/stress)

`./stress -n -1 -c 10000  -m POST https://www.google.com/`

Use stress to run 10,000 concurrent times for 2 minutes, then shut down, and then use www.speedtest.net to test the speed. The downlink speed is only 20Mbps at most, but before the concurrent speed test, the downlink speed can be above 250Mbps.

**Comment by zonyitoo** [comment] 2022-01-18 04:48
You don't need to test every commits I made. I will tell you when it is ready for test. And you can stop mentioning tun2socks.

**Comment by zonyitoo** [comment] 2022-01-18 05:24
Except for `tun`, all the other local client interfaces have the same throughput as direct connections in a 1000M network.

Let me explain more about the current problems found in `tun` local:

1. `smoltcp` requires a Virtual Interface structure to drive the state machine of all TCP sockets, so packets input / output have to be transferred to this virtual interface with channels (memory copies).
2. `smoltcp`'s Virtual Interface managers all the allocated sockets in one single structure and drive the state machines every time when `poll` was called. So if we want to use it in multi-thread program, we have to use `Mutex` to protect this interface, or manager. Every call of `read`s and `write`s have to take that lock first. `poll` must be called repeatedly in very short interval (in milliseconds).

But since my virtual machine only have 1 core, so all the tasks are now running in 1 thread, which means that they don't need to compete with each others about this lock. I don't want to make a conclusion that `smoltcp` can only run in that lower throughtput, so I will keep investigating.

If you have any thoughts about where is the bottleneck of the program, please comments.

**Comment by zonyitoo** [comment] 2022-01-20 07:24
@f4nff Please test the latest commit and see if it solves this issue in your environment.

**Comment by f4nff** [comment] 2022-01-20 10:40
[https://github.com/shadowsocks/shadowsocks-rust/actions/runs/1722149352](https://github.com/shadowsocks/shadowsocks-rust/actions/runs/1722149352)

download tests：
<img width="523" alt="image" src="https://user-images.githubusercontent.com/19538878/150322817-3584a6e6-e71b-4a4b-8c85-d6c56ef6d02f.png">

After the tcp concurrency test, the speed is measured, and the speed drops a lot. Just started the speed test with 200Mbps+, now only...

[golang-tunsocks](https://github.com/xjasonlyu/tun2socks)

<img width="528" alt="image" src="https://user-images.githubusercontent.com/19538878/150323201-830d283b-c58f-4345-a052-d5ce35647314.png">

**Comment by zonyitoo** [comment] 2022-01-20 10:50
This is the test locally in my virtual machine (x86_64):

```
Connecting to host 10.43.57.87, port 5201
[  4] local 10.255.0.1 port 34818 connected to 10.43.57.87 port 5201
[ ID] Interval           Transfer     Bandwidth       Retr  Cwnd
[  4]   0.00-1.00   sec  61.7 MBytes   517 Mbits/sec    0   88.4 KBytes
[  4]   1.00-2.00   sec  61.3 MBytes   514 Mbits/sec    0   88.4 KBytes
[  4]   2.00-3.00   sec  56.4 MBytes   473 Mbits/sec    0   88.4 KBytes
[  4]   3.00-4.00   sec  56.4 MBytes   473 Mbits/sec    0   88.4 KBytes
[  4]   4.00-5.00   sec  58.7 MBytes   493 Mbits/sec    0   88.4 KBytes
[  4]   5.00-6.00   sec  55.6 MBytes   466 Mbits/sec    0   88.4 KBytes
[  4]   6.00-7.00   sec  60.6 MBytes   509 Mbits/sec    0   88.4 KBytes
[  4]   7.00-8.00   sec  60.9 MBytes   510 Mbits/sec    0   88.4 KBytes
[  4]   8.00-9.00   sec  58.9 MBytes   494 Mbits/sec    0   88.4 KBytes
[  4]   9.00-10.00  sec  57.0 MBytes   478 Mbits/sec    0   88.4 KBytes
- - - - - - - - - - - - - - - - - - - - - - - - -
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-10.00  sec   587 MBytes   493 Mbits/sec    0             sender
[  4]   0.00-10.00  sec   587 MBytes   492 Mbits/sec                  receiver

iperf Done.
```

Why your environment so special? :(

**Comment by f4nff** [comment] 2022-01-20 11:05
1:
`./stress -n -1 -c 10000 -m POST https://www.google.com/`
2: tests speedtest

**Comment by dev4u** [comment] 2022-01-20 11:20
> 1:
> `./stress -n -1 -c 10000 -m POST https://www.google.com/`
> 2: tests speedtest

两点小建议，不妨参考一下:
1.不要测试带cdn的域名地址，因为请求到哪带有不确定性。
2.一般来说，对一个工具做性能压测，会通过本地端口来评估，因为网络是个很不稳定的因素。

**Comment by f4nff** [comment] 2022-01-20 11:26
@dev4u   你的建议看似有点道理，其实没多大意义，
这个项目我测试好几天了，你说那些因素我基本都考虑在内了，
结论就是：目前shadowsocks-rust-sslocal-tun模式存在内存，性能问题。

**Comment by dev4u** [comment] 2022-01-20 12:11
@f4nff 你试试改短`net.netfilter.nf_conntrack_tcp_timeout_established=7440`这个设置。

**Comment by zonyitoo** [comment] 2022-01-20 17:13
![image](https://user-images.githubusercontent.com/1067951/150388205-496ae9c2-962e-4284-bfa7-5ca0c9849a0c.png)

Actually speedtest working quite well in my environment. You may test it again with the latest build.

**Comment by zonyitoo** [comment] 2022-01-21 05:00
## Memory Consumption

According to the analysis above, we can sure that there is no leak in the application code. Memory Allocators generally won't return memory to system for increasing thoughtput. In this project, we are using Rust's default Allocator, which is exactly the one in glibc.

For users who cares a lot about the memory consumption, just use jemalloc with a very conservative strategy:

```bash
cargo build --feature "local-tun jemallocator" --release
```

Run the program with `MALLOC_CONF` environment variable set to extremely conservative: `narenas:1,tcache:false,dirty_decay_ms:0,muzzy_decay_ms:0`.

```
export MALLOC_CONF='narenas:1,tcache:false,dirty_decay_ms:0,muzzy_decay_ms:0'
./target/release/sslocal
```

In my local test environment (Debian), with UDP stress test enabled, `RES` is very stable in ~13000:

![image](https://user-images.githubusercontent.com/1067951/150468741-7b9b584f-e3c9-4677-a8ab-ed480e347913.png)

But this strategy will definitely hurt performance, I don't think this is worth to do.

### References

1. http://jemalloc.net/jemalloc.3.html#tuning

**Comment by f4nff** [comment] 2022-01-21 06:27
[sslocal](https://github.com/shadowsocks/shadowsocks-rust/actions/runs/1727137949)

1:speedtest before concurrency testing
<img width="545" alt="image" src="https://user-images.githubusercontent.com/19538878/150474355-b8e28589-cd38-4527-88df-b26ed06a147f.png">

**Comment by f4nff** [comment] 2022-01-21 06:28
It's not convenient for me to test now, I will retest later

**Comment by zonyitoo** [comment] 2022-01-25 06:45
Did you got any results? @f4nff

**Comment by f4nff** [comment] 2022-01-29 14:11
<img width="524" alt="image" src="https://user-images.githubusercontent.com/19538878/151664176-05c976b9-3d03-40ad-86af-2ff2c94d99e1.png">
After the concurrent test, the speed is still reduced.
After I use https://github.com/xjasonlyu/tun2socks for tcp speed measurement, the speed can still get more than 300M,

**Comment by f4nff** [comment] 2022-01-29 14:12
However, this version is obviously much faster than before, but after the concurrent udp memory, it still occupies a lot and will not be released. Generally speaking, it is still not as good as https://github.com/xjasonlyu/tun2socks

**Comment by f4nff** [comment] 2022-01-29 14:13
<img width="328" alt="image" src="https://user-images.githubusercontent.com/19538878/151664255-09353cdd-9f2d-4d97-9f5b-7e005fdd37da.png">

**Comment by f4nff** [comment] 2022-01-29 15:17
I analyzed it, and what **tun2socks-go** uses is:
`tun -device tun1 -proxy socks5://[::1]:1080 -loglevel silent -stats :9000`
**ssloacl** is using:
`sslocal --protocol tun -s "[::1]:1081" -m "none" -k "" --outbound-bind-interface lo --tun-interface-name tun1 -U --udp-timeout 60 - -udp-max-associations 65535`
In addition to tun's own protocol stack processing, the handshake protocol is also different. There may be two reasons why sslocal performs tcp concurrent speed measurement and then slows down. There is a problem with the tun protocol stack itself, but the handshake `-s "[::1]:1081 The problem of " -m "none" -k ""`, one uses `socks5` and one uses `ss://none`


The author is reluctant to add socks5 to the handshake protocol, so I can't give more exact comparison data now.

**Comment by zonyitoo** [comment] 2022-01-29 17:05
I just couldn't reproduce it locally because I got 500M in speedtest.net (this is the maximum bandwidth of my public network). So I still think there is just something special only happen in your environment. You can try to run iperf / iperf3 on local network to avoid the bottleneck of your outbound network (300M) for reducing variables in your environment.

The current TCP stack still have some performance problems comparing to system's builtin, but it only happens when reaching to 1000M. I will continue working on this problem.

And I don't think the protocol is the problem because R4S should easily run encryption protocols when handling 1000M bandwidth.

Oh the other hand, the memory consumption problem should already have a conclusion.

BTW, did you have software development background? If so, could you just help to findout what exactly differences between tun2socks and sslocal in your local environment? It is very hard to locate the exact problem if I couldn't reproduce it locally. The optimization I just did is based on imagination and experiences.

**Closed** 2022-01-29 17:19 UTC

**Comment by f4nff** [comment] 2022-01-30 06:42
I don't know how to develop, but I have been in charge of testing. I think you'd better add socks5 protocol, so that I can give you accurate test feedback. Besides, socks5 is used very frequently.
