### ISSUE TITLE
ssurl is broken

### ISSUE THREAD

**Issue by cfal** [shadowsocks/shadowsocks-rust#284] opened 2020-08-08 09:34 UTC
`./ssurl --encode config.json` returns:

`error: The argument '--encode <ENCODE>' cannot be used with one or more of the other specified arguments`

After commenting out these lines, it works: https://github.com/shadowsocks/shadowsocks-rust/blob/master/src/bin/ssurl.rs#L78-L80

**Comment by Stzx** [comment] 2020-08-08 10:26
https://github.com/shadowsocks/shadowsocks-rust/blob/380126afd0300543bb519472bce3ca43a3a18e4f/src/bin/ssurl.rs#L78-L80

Introduced by a12c171602434ff236422c482a215756554a4a2b

But `ENCODE` and `DECODE` have mutually exclusive declarations, let us ask @zonyitoo

**Comment by Stzx** [comment] 2020-08-08 12:06
I re-checked the `clap` documentation and found that it was a usage problem. 😅

**Comment by zonyitoo** [comment] 2020-08-08 14:46
Hmm, so clap doesn't allow to set two arguments to be `conficts_with` each other? Can you give us some references to the related document?

**Comment by Stzx** [comment] 2020-08-08 14:56
@zonyitoo https://docs.rs/clap/2.33.2/clap/struct.Arg.html#method.conflicts_with

see `NOTE`

**Comment by zonyitoo** [comment] 2020-08-08 14:58
> NOTE: Defining a conflict is two-way, but does not need to defined for both arguments (i.e. if A conflicts with B, defining A.conflicts_with(B) is sufficient. You do not need need to also do B.conflicts_with(A))

:(

**Comment by lolilolicon** [comment] 2020-10-17 16:34
FYI, `ssurl --decode ss://...` still doesn't work.
It's clap.
I removed the (the one remaining) `conflicts_with` bit and I was able to use `--decode`.
But the fix isn't the solution, since now `--decode` and `--encode` can both be specified on the cmdline.

**Comment by zonyitoo** [comment] 2020-10-17 16:37
> FYI, `ssurl --decode ss://...` still doesn't work.
> It's clap.
> I removed the (the one remaining) `conflicts_with` bit and I was able to use `--decode`.
> But the fix isn't the solution, since now `--decode` and `--encode` can both be specified on the cmdline.

Yes, BUG confirmed.

**Comment by zonyitoo** [comment] 2020-10-17 16:49
https://github.com/shadowsocks/shadowsocks-rust/blob/8eeda75a7206924260c7a7e20b24635d545ea8ac/src/bin/ssurl.rs#L78-L80

These lines makes both `--encode` and `--decode` required internally, which is very unexpected..

Will be fixed in the next release.

**Closed** 2020-10-17 16:51 UTC
